import { Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { createReadStream } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { join, resolve } from 'path';

// Where uploaded files live. It sits next to the source code, and is listed
// in .gitignore so resumes never get committed.
const UPLOAD_DIR = resolve(process.cwd(), 'uploads');

// Everything that touches stored files goes through this one service.
// That is deliberate: to move resumes to AWS S3 later, this is the only
// file that changes - nothing that calls it has to know where files live.
@Injectable()
export class StorageService {
  // Saves the uploaded file and returns the "key" we store in the database.
  // The key is the path inside the uploads folder, not a full path, so the
  // database does not depend on where the project happens to sit on disk.
  async saveResume(userId: string, file: Express.Multer.File) {
    // A random name means one user cannot overwrite another user's file,
    // and nobody can guess a filename. Grouping by user id keeps it tidy.
    const key = `resumes/${userId}/${randomUUID()}.pdf`;
    const fullPath = join(UPLOAD_DIR, key);

    // recursive: true creates the resumes/<userId> folders if they are new.
    await mkdir(join(UPLOAD_DIR, 'resumes', userId), { recursive: true });
    await writeFile(fullPath, file.buffer);

    return key;
  }

  // Opens a stored file for reading. The controller pipes this to the browser
  // only after checking the person is allowed to see it.
  readResume(key: string) {
    return createReadStream(this.safePath(key));
  }

  // Keys are generated by saveResume above, so they are already safe. This
  // checks anyway: if a bad key ever reached the database, "../../" in it
  // could otherwise read files from anywhere on the server.
  private safePath(key: string) {
    const fullPath = resolve(UPLOAD_DIR, key);

    if (!fullPath.startsWith(UPLOAD_DIR)) {
      throw new Error('Invalid file key');
    }

    return fullPath;
  }
}
